/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arturviader.restaurantesswingartur;

import Code.Metodos;
import com.arturviader.restaurantesswingartur.Data.Plato;
import com.arturviader.restaurantesswingartur.Data.Restaurante;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Ventana de borrar un plato
 * @author arturviadermataix
 */
public class FrmBorrarPlato extends javax.swing.JDialog {
    ArrayList<Plato> platos;
    int seleccion = -1;
    boolean hayplatos = false;
  
    /**
     * Creates new form FrmBorrarPlato
     */
    public FrmBorrarPlato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Se leen los platos
        platos = Metodos.leePlatos();
        if(platos.size()>0)
        {
            hayplatos=true;
            for(Plato elplato:platos)
            {
                //Se añaden los platos al combobox
                cPlato.addItem(elplato.getNombre());
            }
        }  
        else
        {
            cPlato.addItem("---NO HAY PLATOS---");
        }
        setLocationRelativeTo(null);
         setVisible(true);
         setSize(92,29);
         setTitle("Eliminar plato");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cPlato = new javax.swing.JComboBox<>();
        bCancelar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Plato");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bCancelar)
                        .addGap(51, 51, 51)
                        .addComponent(bBorrar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bBorrar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón de borrar
     * @param evt 
     */
    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
        if(hayplatos && cPlato.getSelectedIndex()>=0)
        {  
            int reply = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas borrar el plato?", "Atención", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                platos.remove(cPlato.getSelectedIndex());
                Metodos.regrabaFicheroPlatos(platos);
                this.dispose();
            }
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    /**
     * Botón de cancelar
     * @param evt 
     */
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cPlato;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
