/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arturviader.restaurantesswingartur;

import com.arturviader.restaurantesswingartur.Data.Memoria;
import javax.swing.JFrame;

/**
 * Ventana del menú
 * @author arturviadermataix
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        super("Menú");
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
        setLocationRelativeTo(null);
        setSize(97,29);
        initComponents();
        if(Memoria.getInstance().getUsuario().equals("admin"))
        {
            lUsuarios.setVisible(true);
            bNuevoUsuario.setVisible(true);
            bBorrarUsuario.setVisible(true);
        }
        else
        {
            lUsuarios.setVisible(false);
            bNuevoUsuario.setVisible(false);
            bBorrarUsuario.setVisible(false);
        }
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bRNuevo = new javax.swing.JButton();
        BRModificar = new javax.swing.JButton();
        BRBorrar = new javax.swing.JButton();
        BRConsultar = new javax.swing.JButton();
        BPNuevo = new javax.swing.JButton();
        BPModificar = new javax.swing.JButton();
        BPBorrar = new javax.swing.JButton();
        BPConsultar = new javax.swing.JButton();
        lUsuarios = new javax.swing.JLabel();
        bNuevoUsuario = new javax.swing.JButton();
        bBorrarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Come, Saborea y Critica");

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("RESTAURANTES");

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("PLATOS");

        bRNuevo.setText("NUEVO");
        bRNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRNuevoActionPerformed(evt);
            }
        });

        BRModificar.setText("MODIFICAR");
        BRModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRModificarActionPerformed(evt);
            }
        });

        BRBorrar.setText("BORRAR");
        BRBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRBorrarActionPerformed(evt);
            }
        });

        BRConsultar.setText("CONSULTAR");
        BRConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRConsultarActionPerformed(evt);
            }
        });

        BPNuevo.setText("NUEVO");
        BPNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPNuevoActionPerformed(evt);
            }
        });

        BPModificar.setText("MODIFICAR");
        BPModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPModificarActionPerformed(evt);
            }
        });

        BPBorrar.setText("BORRAR");
        BPBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPBorrarActionPerformed(evt);
            }
        });

        BPConsultar.setText("CONSULTAR");
        BPConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPConsultarActionPerformed(evt);
            }
        });

        lUsuarios.setForeground(new java.awt.Color(0, 0, 204));
        lUsuarios.setText("USUARIOS");

        bNuevoUsuario.setText("NUEVO");
        bNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoUsuarioActionPerformed(evt);
            }
        });

        bBorrarUsuario.setText("BORRAR");
        bBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BRConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(BRBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bRNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BRModificar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BPNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BPModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BPBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BPConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBorrarUsuario)
                            .addComponent(bNuevoUsuario)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lUsuarios)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lUsuarios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRNuevo)
                    .addComponent(BPNuevo)
                    .addComponent(bNuevoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRModificar)
                    .addComponent(BPModificar)
                    .addComponent(bBorrarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRBorrar)
                    .addComponent(BPBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRConsultar)
                    .addComponent(BPConsultar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón nuevo restaurante
     * @param evt 
     */
    private void bRNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRNuevoActionPerformed
        FrmNuevoRestaurante frmnuevorestaurante;
        this.setVisible(false);
        frmnuevorestaurante = new FrmNuevoRestaurante(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_bRNuevoActionPerformed

    /**
     * Botón nuevo plato
     * @param evt 
     */
    private void BPNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPNuevoActionPerformed
        FrmNuevoPlato frmnuevoplato;
        this.setVisible(false);
        frmnuevoplato = new FrmNuevoPlato(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_BPNuevoActionPerformed

    /**
     * Botón modificar plato
     * @param evt 
     */
    private void BPModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPModificarActionPerformed
        // TODO add your handling code here:
        FrmModificarPlato frmmodificarplato;
        this.setVisible(false);
        frmmodificarplato = new FrmModificarPlato(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_BPModificarActionPerformed

    /**
     * Botón borrar plato
     * @param evt 
     */
    private void BPBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPBorrarActionPerformed
        // TODO add your handling code here:
        FrmBorrarPlato frmborrarplato;
        this.setVisible(false);
        frmborrarplato = new FrmBorrarPlato(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_BPBorrarActionPerformed

    /**
     * Botón consultar plato
     * @param evt 
     */
    private void BPConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPConsultarActionPerformed
        FrmVerPlatos frmconsultarplato;
        this.setVisible(false);
        frmconsultarplato = new FrmVerPlatos(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_BPConsultarActionPerformed

    /**
     * Botón modificar plato
     * @param evt 
     */
    private void BRModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRModificarActionPerformed
        FrmModificaRestaurante frmmodificarestaurante;
        this.setVisible(false);
        frmmodificarestaurante = new FrmModificaRestaurante(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_BRModificarActionPerformed

    /**
     * Botón borrar restaurante
     * @param evt 
     */
    private void BRBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRBorrarActionPerformed
        FrmBorrarRestaurante frmborrarrestaurante;
        this.setVisible(false);
        frmborrarrestaurante = new FrmBorrarRestaurante(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_BRBorrarActionPerformed

    /**
     * Botón ver restaurantes
     * @param evt 
     */
    private void BRConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRConsultarActionPerformed
        FrmVerRestaurantes frmverrestaurantes;
        this.setVisible(false);
        frmverrestaurantes = new FrmVerRestaurantes(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_BRConsultarActionPerformed

    /**
     * Botón nuevo usuario
     * @param evt 
     */
    private void bNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoUsuarioActionPerformed
        FrmNuevoUsuario frmnuevousuario;
        this.setVisible(false);
        frmnuevousuario = new FrmNuevoUsuario(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_bNuevoUsuarioActionPerformed

    /**
     * Botón borrar usuario
     * @param evt 
     */
    private void bBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarUsuarioActionPerformed
        FrmBorrarUsuario frmborrarusuario;
        this.setVisible(false);
        frmborrarusuario = new FrmBorrarUsuario(this,true);
        this.setVisible(true);
    }//GEN-LAST:event_bBorrarUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPBorrar;
    private javax.swing.JButton BPConsultar;
    private javax.swing.JButton BPModificar;
    private javax.swing.JButton BPNuevo;
    private javax.swing.JButton BRBorrar;
    private javax.swing.JButton BRConsultar;
    private javax.swing.JButton BRModificar;
    private javax.swing.JButton bBorrarUsuario;
    private javax.swing.JButton bNuevoUsuario;
    private javax.swing.JButton bRNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lUsuarios;
    // End of variables declaration//GEN-END:variables
}
