/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arturviader.restaurantesswingartur;

import Code.Metodos;
import com.arturviader.restaurantesswingartur.Data.Restaurante;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Ventana de modificar restaurante
 * @author arturviadermataix
 */
public class FrmModificaRestaurante extends javax.swing.JDialog {

    /**
     * Creates new form FrmModificaRestaurante
     */
    ArrayList<Restaurante> restaurantes;
    Boolean hayrestaurantes = false;
    Boolean seleccionado = false;
    String nombreantiguo;
    public FrmModificaRestaurante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        restaurantes = Metodos.leeRestaurantes();
        bAceptar.setEnabled(false);
        if(restaurantes.size()>0)
        {
            hayrestaurantes = true;
        }
        for (Restaurante elrestaurante:restaurantes)
        {
            cRestaurante.addItem(elrestaurante.getNombre());
        }
        if(!hayrestaurantes)
        {
            cRestaurante.addItem("-----No hay restaurantes");
        }
        setLocationRelativeTo(null);
        setVisible(true);
        setSize(97,29);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cRestaurante = new javax.swing.JComboBox<>();
        cSeleccionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tPoblacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Restaurante a modificar");

        jLabel2.setText("Restaurante");

        cSeleccionar.setText("Seleccionar");
        cSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSeleccionarActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Datos del restaurante a modificar");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Población:");

        jLabel6.setText("Teléfono:");

        jLabel7.setText("Nombre:");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSeleccionar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tDireccion))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tPoblacion)
                                    .addComponent(tTelefono))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(bCancelar)
                .addGap(73, 73, 73)
                .addComponent(bAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bAceptar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón de seleccionar
     * @param evt 
     */
    private void cSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSeleccionarActionPerformed
       if(hayrestaurantes && cRestaurante.getSelectedIndex()>=0)
        {
            //Se muestra el plato
            cRestaurante.setEnabled(false);
            bAceptar.setEnabled(true);
            nombreantiguo = restaurantes.get(cRestaurante.getSelectedIndex()).getNombre(); 
            tNombre.setText(restaurantes.get(cRestaurante.getSelectedIndex()).getNombre());
            tDireccion.setText(restaurantes.get(cRestaurante.getSelectedIndex()).getDireccion());
            tPoblacion.setText(restaurantes.get(cRestaurante.getSelectedIndex()).getPoblacion());
            tTelefono.setText(restaurantes.get(cRestaurante.getSelectedIndex()).getTelefono());
            seleccionado = true;
        }
        
        
        
        
        
    }//GEN-LAST:event_cSeleccionarActionPerformed

    /**
     * Botón de aceptar
     * @param evt 
     */
    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
        boolean hacer = true;
          if(hayrestaurantes && cRestaurante.getSelectedIndex()>=0 && seleccionado)
        {
            //Se actualiza el plato de la lista
            if(!(nombreantiguo.equals(tNombre.getText())))
            {
                if(Metodos.buscaRestaurante(restaurantes,tNombre.getText()))
                {
                    JOptionPane.showMessageDialog(this, "Ya existe un plato con este nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                    hacer = false;
                }
                else
                {
                    //Si el nombre del restaurante ha cambiado se actualizan los platos de este en cascada
                    Metodos.actualizaRestauranteCascada(nombreantiguo,tNombre.getText());
                }
            }
             
            if(hacer)
            {
                restaurantes.get(cRestaurante.getSelectedIndex()).setNombre(tNombre.getText());
                restaurantes.get(cRestaurante.getSelectedIndex()).setPoblacion(tPoblacion.getText());
                restaurantes.get(cRestaurante.getSelectedIndex()).setDireccion(tDireccion.getText());
                restaurantes.get(cRestaurante.getSelectedIndex()).setTelefono(tTelefono.getText());
                //Se reescribe el fichero
                Metodos.regrabaFicheroRestaurantes(restaurantes);
               
                
                this.dispose();
            }
            
        }
        
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * Botón de cancelar
     * @param evt 
     */
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cRestaurante;
    private javax.swing.JButton cSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tPoblacion;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
