/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arturviader.restaurantesswingartur;

import Code.Metodos;
import com.arturviader.restaurantesswingartur.Data.Plato;
import com.arturviader.restaurantesswingartur.Data.Restaurante;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Ventana de modificar plato
 * @author arturviadermataix
 */
public class FrmModificarPlato extends javax.swing.JDialog {

    ArrayList<Plato> platos;
    int seleccion = -1;
    boolean hayplatos = false;
    boolean seleccionado = false;
    String nombreantiguo;
    ArrayList<Restaurante> restaurantes;
    /**
     * Creates new form FrmModificarPlato
     */
    public FrmModificarPlato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Se leen los pltos y se cargan en el combo
        platos = Metodos.leePlatos();
        bAceptar.setEnabled(false);
        if(platos.size()>0)
        {
            hayplatos=true;
            for(Plato elplato:platos)
            {
                cPlato.addItem(elplato.getNombre());
            }
        }  
        else
        {
            cPlato.addItem("---NO HAY PLATOS---");
        }
        //Se leen los restaurantes y se cargan en el combo
        restaurantes = Metodos.leeRestaurantes();
        for (Restaurante elrestaurante:restaurantes)
        {
            cRestaurante.addItem(elrestaurante.getNombre());
        }
         setLocationRelativeTo(null);
         setVisible(true);
         setSize(92,29);
         setTitle("Modificar plato");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cPlato = new javax.swing.JComboBox<>();
        BSeleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        cRestaurante = new javax.swing.JComboBox<>();
        cTipo = new javax.swing.JComboBox<>();
        tPrecio = new javax.swing.JSpinner();
        tNota = new javax.swing.JSpinner();
        tFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Plato:");

        cPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPlatoActionPerformed(evt);
            }
        });

        BSeleccionar.setText("Seleccionar");
        BSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("PLATO A MODIFICAR");

        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Datos del plato a modificar");

        jLabel4.setText("Nombre del plato:");

        jLabel5.setText("Restaurante:");

        jLabel6.setText("Tipo");

        jLabel7.setText("Precio");

        jLabel8.setText("Nota");

        jLabel9.setText("Fecha de prueba");

        cTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrante", "Segundo", "Postre" }));

        tFecha.setEditable(false);
        tFecha.setEnabled(false);

        jLabel10.setText("Eur");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel9))
                                .addGap(131, 131, 131)
                                .addComponent(bAceptar)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(BSeleccionar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tNombre)
                                        .addComponent(cRestaurante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cTipo, 0, 201, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tNota, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSeleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(bAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPlatoActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        // TODO add your handling code here:
        Boolean hacer = true;
        if(hayplatos && cPlato.getSelectedIndex()>=0 && seleccionado)
        {
            if(!(nombreantiguo.equals(tNombre.getText())))
            {
                if(Metodos.buscaPlato(platos,tNombre.getText()))
                {
                    JOptionPane.showMessageDialog(this, "Ya existe un plato con este nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                    hacer = false;
                }
            }
            //Se actualiza el plato de la lista
            
            if(hacer){
                platos.get(cPlato.getSelectedIndex()).setNombre(tNombre.getText());
                platos.get(cPlato.getSelectedIndex()).setRestaurante(cRestaurante.getSelectedItem().toString());
                platos.get(cPlato.getSelectedIndex()).setTipo(cRestaurante.getSelectedIndex());
                platos.get(cPlato.getSelectedIndex()).setPrecio((Integer) tPrecio.getValue());
                platos.get(cPlato.getSelectedIndex()).setNota((Integer) tNota.getValue());
                platos.get(cPlato.getSelectedIndex()).setFecha(new Date());
                //Se reescribe el fichero
                Metodos.regrabaFicheroPlatos(platos);
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * Botón de seleccionar plato
     * @param evt 
     */ 
    private void BSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSeleccionarActionPerformed
        // TODO add your handling code here:
        if(hayplatos)
        {
            
            seleccion = cPlato.getSelectedIndex();
            if(seleccion>=0)
            {
                 cPlato.setEnabled(false);
                 seleccionado = true;
                 muestraplato(cPlato.getSelectedIndex());     
                 bAceptar.setEnabled(true);
                 nombreantiguo = platos.get(cPlato.getSelectedIndex()).getNombre();
            }
        }
    }//GEN-LAST:event_BSeleccionarActionPerformed

    /**
     * Botón de cerrar
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Muestra el plato
     * @param queplato 
     */
    private void muestraplato(int queplato)
    {
      
        tNombre.setText(platos.get(queplato).getNombre());
            
        cRestaurante.setSelectedIndex(dimePosRestaurante(platos.get(queplato).getRestaurante()));
        
        cTipo.setSelectedIndex(platos.get(queplato).getTipo());
        
        tPrecio.setValue(platos.get(queplato).getPrecio());
        
        tNota.setValue(platos.get(queplato).getNota());
        
        tFecha.setText(Metodos.fechaaString(platos.get(queplato).getFecha()));
       
    }

    /**
     * Dice la posición en la lista de un restaurante buscando por el nombre
     * @param restaurante Nombre del restaurante
     * @return 
     */
    private int dimePosRestaurante(String restaurante)
    {
        boolean sal = false;
        boolean encontrado = false;
        int cont = 0;
        while(!sal)
        {
            if(restaurantes.get(cont).getNombre().equals(restaurante))
            {
                encontrado = true;
                sal = true;
            }
            else
            {
                cont+=1;
                if(cont>=restaurantes.size())
                {
                    sal = true;
                }
            }
        }
        if(encontrado)
        {
            return cont;
        }
        else
        {
            return -1;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSeleccionar;
    private javax.swing.JButton bAceptar;
    private javax.swing.JComboBox<String> cPlato;
    private javax.swing.JComboBox<String> cRestaurante;
    private javax.swing.JComboBox<String> cTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tFecha;
    private javax.swing.JTextField tNombre;
    private javax.swing.JSpinner tNota;
    private javax.swing.JSpinner tPrecio;
    // End of variables declaration//GEN-END:variables
}
