/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arturviader.restaurantesswingartur;

import Code.Metodos;
import com.arturviader.restaurantesswingartur.Data.Plato;
import com.arturviader.restaurantesswingartur.Data.Restaurante;
import java.util.ArrayList;

/**
 * Ventana de ver platos
 * @author arturviadermataix
 */
public class FrmVerPlatos extends javax.swing.JDialog {
    ArrayList<Restaurante> restaurantes;
    ArrayList<Plato> platos;
    ArrayList<Plato> platosfiltrados;
    int posicion = -1;
    /**
     * Creates new form frmVerPlatos
     */
    public FrmVerPlatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Lee los restaurantes y los añade al combo
        restaurantes = Metodos.leeRestaurantes();
        cRestaurante.addItem("--Seleccciona un Restaurante--");
        for (Restaurante elrestaurante:restaurantes)
        {
            cRestaurante.addItem(elrestaurante.getNombre());
        }
        //Lee los platos
        platos = Metodos.leePlatos();
        platosfiltrados = new ArrayList<>();
        filtra();
        posicion = 0;
        //Muestra posición actual
        muestraPosicion();
        setLocationRelativeTo(null);
        setVisible(true);
        setSize(418,339);
        setTitle("Ver platos");
    }

    /**
     * Filtra platos por restaurante y por tipo
     */
    private void filtra()
    {
        boolean meteplato;
        String nombreRestaurante;
        platosfiltrados.clear();
        for(Plato elplato:platos)
        {
            meteplato=true;
            if(cRestaurante.getSelectedIndex()>0)
            {
                nombreRestaurante = restaurantes.get(cRestaurante.getSelectedIndex() - 1).getNombre();
                System.out.println(nombreRestaurante);
                if(!(elplato.getRestaurante().equals(nombreRestaurante)))
                {
                    meteplato=false;
                }
            }
            
            if(meteplato)
            {
                if(cTipo.getSelectedIndex()>0)
                {
                    if(!(elplato.getTipo() == cTipo.getSelectedIndex()-1))
                    {
                        meteplato=false;
                    }
                }
            }
            
            if(meteplato)
            {
                platosfiltrados.add(elplato);
            }          
        }
    }
    
    //Muestra posición actual
    private void muestraPosicion()
    {
        if(platosfiltrados.size()>0)
        {
            if(posicion==platosfiltrados.size()-1)
            {
                bSiguiente.setEnabled(false);
            }
            else
            {
                bSiguiente.setEnabled(true);
            }
            
            if(posicion==0){
                bAnterior.setEnabled(false);
            }
            else
            {
                bAnterior.setEnabled(true);
            }
            
            if(posicion>=0 && posicion<platosfiltrados.size())
            {
                lNombre.setText(platosfiltrados.get(posicion).getNombre());
                lRestaurante.setText(platosfiltrados.get(posicion).getRestaurante());
                lTipo.setText(Metodos.dimetipo(platosfiltrados.get(posicion).getTipo()));
                lPrecio.setText(Integer.toString(platosfiltrados.get(posicion).getPrecio()));
                lNota.setText(Integer.toString(platosfiltrados.get(posicion).getNota()));
                lFecha.setText(Metodos.fechaaString(platosfiltrados.get(posicion).getFecha()));
            }
            else
            {
                vaciacampos();
            }
        }
        else
        {
            bSiguiente.setEnabled(false);
            bAnterior.setEnabled(false);
            vaciacampos();
        }
    }
    
    /**
     * Vacia los campos
     */
    private void vaciacampos()
    {
        lNombre.setText("");
        lRestaurante.setText("");
        lTipo.setText("");
        lPrecio.setText("");
        lNota.setText("");
        lFecha.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cRestaurante = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        bFiltrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lRestaurante = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lPrecio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lNota = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lFecha = new javax.swing.JLabel();
        cTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Restaurante:");

        jLabel2.setText("Tipo de plato:");

        bFiltrar.setText("Filtrar");
        bFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        lNombre.setText("jLabel4");

        jLabel5.setText("Restaurante:");

        lRestaurante.setText("jLabel6");

        jLabel7.setText("Tipo de plato:");

        lTipo.setText("jLabel8");

        jLabel9.setText("Precio:");

        lPrecio.setText("jLabel10");

        jLabel11.setText("Nota:");

        lNota.setText("jLabel12");

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bAnterior.setText("<< Anterior");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bSiguiente.setText("Siguiente >>");
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        jLabel13.setText("Fecha:");

        lFecha.setText("jLabel14");

        cTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un Tipo de Plato--", "Entrante", "Segundo", "Postre" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cRestaurante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cTipo, 0, 252, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lTipo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lRestaurante))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(69, 69, 69)
                                    .addComponent(lNombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lFecha)
                                    .addComponent(lNota)
                                    .addComponent(lPrecio)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bSalir)
                        .addGap(68, 68, 68)
                        .addComponent(bAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(bSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(bFiltrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bFiltrar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRestaurante)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lNota))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalir)
                    .addComponent(bAnterior)
                    .addComponent(bSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón de siguiente
     * @param evt 
     */
    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
        posicion += 1;
        muestraPosicion();
    }//GEN-LAST:event_bSiguienteActionPerformed

    /**
     * Botón de filtrar
     * @param evt 
     */
    private void bFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarActionPerformed
       filtra();
       posicion = 0;
       muestraPosicion();
    }//GEN-LAST:event_bFiltrarActionPerformed

    /**
     * Botón anterior
     * @param evt 
     */
    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
       posicion -=1;
       muestraPosicion();
    }//GEN-LAST:event_bAnteriorActionPerformed

    /**
     * Botón salir
     * @param evt 
     */
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bFiltrar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JComboBox<String> cRestaurante;
    private javax.swing.JComboBox<String> cTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNota;
    private javax.swing.JLabel lPrecio;
    private javax.swing.JLabel lRestaurante;
    private javax.swing.JLabel lTipo;
    // End of variables declaration//GEN-END:variables
}
